In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # create an array from a list
print("Array a:", a)

Array a: [1 2 3]


In [3]:
b = np.arange(0, 20, 3) # create an array with evenly spaced values
print("Array b:", b)

Array b: [ 0  3  6  9 12 15 18]


In [4]:
c = np.zeros((2,3)) # Create an array filled with zeros
print("Array c:\n", c)

Array c:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c = np.zeros((2,3), dtype=int) # Create an array filled with zeros
print("Array c:\n", c)

Array c:
 [[0 0 0]
 [0 0 0]]


In [7]:
e = np.ones((3,2)) # Create an array filled with ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
f = np.eye(4) # create an identity matrix
print("identity matrix f:\n", f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create Array manipulation functions

In [9]:
a1 = np.array([1,2,3]) #Reshape an array
reshaped = np.reshape(a1,(1,3))
print("reshaped array: ", reshaped)

reshaped array:  [[1 2 3]]


In [10]:
a1 = np.array([1,2,3]) #Reshape an array
reshaped = np.reshape(a1,(3,1))
print("reshaped array: ", reshaped)

reshaped array:  [[1]
 [2]
 [3]]


In [11]:
# flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1) #flatten to 1D array
print("flattened array: ",flattened)

flattened array:  [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) #transpose the array
print("transposed array:\n ",transposed)

transposed array:
  [[1 3]
 [2 4]]


In [13]:
a2 = np.array([1,2]) #Stack arrays vertically
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a & b vertically
print("stacked arrays:\n", stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [14]:
a2 = np.array([1,2]) #Stack arrays horizontal
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) # stack a & b horizontal
print("stacked arrays:\n", stacked)

stacked arrays:
 [1 2 3 4]


Mathematical Functions

In [16]:
#add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2) #add 2 to each element
print("added 2 to g:", added)

added 2 to g: [3 4 5 6]


In [17]:
# square each element
squared = np.power(g,2) # square each element
print("square g:", squared)

square g: [ 1  4  9 16]


In [18]:
# square root of each element
sqrt_val = np.sqrt(g) #square root of each element
print("square root of g:", sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [19]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [20]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) # dot product of a & g
print("dot product of a1 & a:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [21]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [22]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) # dot product of a & g
print("dot product of a1 & a:", dot_product)

dot product of a1 & a: 14


Statistical Functions

In [23]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("mean of s:", mean)

mean of s: 2.5


In [24]:
# standard deviation of an array
var = np.var(s)
print("variance of s:", var)

variance of s: 1.25


In [27]:
# standard deviation of an array
std_dev = np.std(s)
print("standard deviation of s:", std_dev)

standard deviation of s: 1.118033988749895


In [28]:
#maximum element of an array
maximum = np.max(s)
print("max of s:", maximum)

max of s: 4


In [29]:
#minimum element of an array
minimum = np.min(s)
print("min of s:", minimum)

min of s: 1


Linear Algebra Functions

In [30]:
# create a matrix
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

Random Sampling Functions

In [31]:
# generate random values between 0 & 1
random_vals = np.random.rand(3)
print("Random value:", random_vals)

Random value: [0.42244521 0.34628704 0.66201049]


In [32]:
#set seed for reproducibility
np.random.seed(0)

#generate random values between 0 & 1
random_vals = np.random.rand(3) # array of 3 random value between 0 & 1
print("random values:", random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [33]:
# generate random integers
rand_ints = np.random.randint(0,10, size=5)
# random integers between 0 & 10
print("random integers:", rand_ints)

random integers: [3 7 9 3 5]


In [39]:
# set seed for reproducibilty
np.random.seed(0)
# generate random integers
rand_int = np.random.randint(0,10,size=5)
print("random integers:", rand_int)

random integers: [5 0 3 3 7]


Boolean and logical functions

In [40]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("all elements True:", all_true)

all elements True: False


In [41]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)
print("all elements True:", all_true)

all elements True: False


In [42]:
any_true = np.any(logical_test)
print("any elements True:", any_true)

any elements True: False


SET OPERATIONS

In [43]:
set_a = np.array([1,2,3,4,5])
set_b = np.array([4,5,6,7,8])
intersection = np.intersect1d(set_a, set_b)
print("intersection of a & b:", intersection)

intersection of a & b: [4 5]


In [44]:
union = np.union1d(set_a, set_b)
print("union of a & b:", union)

union of a & b: [1 2 3 4 5 6 7 8]


Array Attribute Functions

In [45]:
a = np.array([1,2,3])
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("shape of a:", shape)
print("size of a:", size)
print("number of dimensions of a:", dimensions)
print("data type of a:", dtype)

shape of a: (3,)
size of a: 3
number of dimensions of a: 1
data type of a: int64


Other Functions

In [46]:
a = np.array([1,2,3])
copied_array = np.copy(a)
print("copied array:", copied_array)

copied array: [1 2 3]


In [47]:
array_size_in_bytes = a.nbytes
print("size of a in bytes", array_size_in_bytes)

size of a in bytes 24


In [48]:
shared = np.shares_memory(a,copied_array)
print("do a & copied_array share memory?", shared)

do a & copied_array share memory? False
