In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.4'

In [4]:
my_list = [0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [24]:
rand(4)

NameError: name 'rand' is not defined

In [25]:
random.rand(4)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(4)  #everytime iy will be different

array([0.24621947, 0.70626526, 0.33606279, 0.22303437])

In [27]:
np.random.rand(4,4)

array([[0.16079837, 0.70252293, 0.96276903, 0.73540801],
       [0.51104597, 0.60886993, 0.70220629, 0.97653814],
       [0.16213137, 0.7724058 , 0.07807457, 0.69028544],
       [0.63683654, 0.57731135, 0.96166868, 0.93483395]])

In [28]:
np.random.rand(2,2)

array([[0.5752445 , 0.35957199],
       [0.53638447, 0.34365602]])

In [30]:
np.random.randint(3)

0

In [35]:
np.random.randint(10,15)

13

In [36]:
np.random.randint(1,5,3)

array([3, 1, 3], dtype=int32)

In [38]:
np.random.randint(1,5,4)

array([1, 1, 2, 2], dtype=int32)

In [39]:
np.random.randint(1,5)

1

In [ ]:
np.random.randint(5,2,3) #1st no.shld be small

ValueError: low >= high

In [42]:
np.random.randint(-5,2,3)

array([-2, -5,  0], dtype=int32)

In [43]:
np.random.randint(10,40,(10,10))

array([[10, 25, 30, 32, 32, 24, 11, 39, 18, 37],
       [13, 32, 38, 36, 34, 10, 24, 32, 12, 37],
       [18, 24, 12, 18, 13, 32, 39, 12, 33, 33],
       [35, 31, 32, 17, 38, 14, 15, 15, 38, 35],
       [29, 37, 17, 13, 37, 26, 10, 29, 30, 28],
       [16, 21, 31, 16, 19, 38, 34, 28, 17, 16],
       [37, 34, 16, 12, 17, 22, 12, 30, 29, 18],
       [31, 34, 17, 15, 35, 24, 31, 37, 22, 11],
       [29, 15, 39, 28, 15, 24, 31, 30, 11, 10],
       [23, 30, 18, 23, 16, 16, 27, 16, 21, 31]], dtype=int32)

In [45]:
ri = np.random.randint(10,40,(10,10))
ri

array([[31, 38, 20, 26, 30, 28, 17, 12, 20, 20],
       [17, 22, 33, 34, 30, 20, 19, 26, 12, 23],
       [28, 19, 16, 32, 21, 20, 34, 23, 13, 29],
       [26, 19, 27, 19, 37, 26, 35, 11, 16, 21],
       [12, 29, 17, 22, 22, 20, 13, 10, 14, 28],
       [31, 19, 15, 27, 11, 26, 14, 19, 12, 21],
       [39, 39, 37, 32, 13, 33, 14, 19, 21, 25],
       [33, 11, 11, 14, 36, 24, 34, 29, 33, 16],
       [25, 37, 22, 27, 34, 22, 36, 36, 28, 37],
       [28, 38, 34, 12, 32, 12, 19, 14, 27, 29]], dtype=int32)

In [47]:
ri = np.random.randint(10,40,(3,5))
ri

array([[34, 18, 36, 19, 13],
       [13, 13, 18, 10, 19],
       [25, 33, 37, 23, 27]], dtype=int32)

In [ ]:
len(ri) # defines length

3

In [ ]:
ri.shape # gives rows and columns

(3, 5)

In [51]:
id(ri)

2622392939504

In [52]:
ri

array([[34, 18, 36, 19, 13],
       [13, 13, 18, 10, 19],
       [25, 33, 37, 23, 27]], dtype=int32)

Slicing in numpy

In [53]:
ri[:] #prints all

array([[34, 18, 36, 19, 13],
       [13, 13, 18, 10, 19],
       [25, 33, 37, 23, 27]], dtype=int32)

In [54]:
ri[1]

array([13, 13, 18, 10, 19], dtype=int32)

In [55]:
ri

array([[34, 18, 36, 19, 13],
       [13, 13, 18, 10, 19],
       [25, 33, 37, 23, 27]], dtype=int32)

In [56]:
ri[0:3]

array([[34, 18, 36, 19, 13],
       [13, 13, 18, 10, 19],
       [25, 33, 37, 23, 27]], dtype=int32)

In [57]:
ri_1 = np.random.randint(10,40,(10,10))
ri_1

array([[12, 20, 20, 31, 34, 27, 14, 18, 14, 15],
       [29, 10, 25, 12, 29, 11, 12, 36, 22, 10],
       [30, 31, 10, 10, 25, 21, 10, 34, 15, 34],
       [34, 21, 24, 16, 32, 15, 32, 13, 22, 21],
       [26, 26, 16, 31, 11, 10, 24, 18, 15, 35],
       [16, 25, 33, 11, 34, 36, 28, 22, 22, 27],
       [10, 15, 35, 32, 33, 22, 13, 31, 35, 26],
       [31, 27, 39, 10, 29, 28, 33, 17, 37, 33],
       [35, 15, 22, 31, 20, 34, 20, 19, 17, 23],
       [29, 22, 28, 13, 29, 17, 36, 12, 32, 29]], dtype=int32)

In [58]:
ri_1.shape

(10, 10)

In [59]:
ri_1 = np.random.randint(10,40,(10,10))
print(ri_1)

[[14 25 19 18 19 33 11 31 14 35]
 [25 28 39 26 26 23 31 17 24 32]
 [17 29 22 32 24 14 34 16 33 30]
 [33 35 35 20 27 32 15 20 21 12]
 [34 35 37 22 26 25 35 14 39 12]
 [28 28 28 26 37 25 34 36 39 32]
 [39 37 34 13 14 22 13 22 37 21]
 [12 36 20 16 38 13 30 20 39 36]
 [19 26 18 36 36 30 33 38 22 18]
 [23 37 15 13 24 12 24 11 26 28]]


In [60]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [61]:
ri_1[3:8]

array([[33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36]], dtype=int32)

In [62]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [65]:
ri_1[3,8]

np.int32(21)

In [66]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [67]:
ri_1[-5]

array([28, 28, 28, 26, 37, 25, 34, 36, 39, 32], dtype=int32)

In [68]:
ri_1[-5,-3]

np.int32(36)

In [69]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [70]:
ri_1[::3]

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [71]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [72]:
ri_1[::-1]

array([[23, 37, 15, 13, 24, 12, 24, 11, 26, 28],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [14, 25, 19, 18, 19, 33, 11, 31, 14, 35]], dtype=int32)

In [ ]:
ri_1[::-5] # backward print

array([[23, 37, 15, 13, 24, 12, 24, 11, 26, 28],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12]], dtype=int32)

In [74]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [75]:
ri_1[2]

array([17, 29, 22, 32, 24, 14, 34, 16, 33, 30], dtype=int32)

In [ ]:
print(ri_1[2]) #specific row and specific column
print(ri_1[:,2])

[17 29 22 32 24 14 34 16 33 30]
[19 39 22 35 37 28 34 20 18 15]


In [77]:
ri_1

array([[14, 25, 19, 18, 19, 33, 11, 31, 14, 35],
       [25, 28, 39, 26, 26, 23, 31, 17, 24, 32],
       [17, 29, 22, 32, 24, 14, 34, 16, 33, 30],
       [33, 35, 35, 20, 27, 32, 15, 20, 21, 12],
       [34, 35, 37, 22, 26, 25, 35, 14, 39, 12],
       [28, 28, 28, 26, 37, 25, 34, 36, 39, 32],
       [39, 37, 34, 13, 14, 22, 13, 22, 37, 21],
       [12, 36, 20, 16, 38, 13, 30, 20, 39, 36],
       [19, 26, 18, 36, 36, 30, 33, 38, 22, 18],
       [23, 37, 15, 13, 24, 12, 24, 11, 26, 28]], dtype=int32)

In [78]:
ri_1[0:3, 0:3]

array([[14, 25, 19],
       [25, 28, 39],
       [17, 29, 22]], dtype=int32)

In [79]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arrange(1,13).reshape(5,4) # 5*4 = 20 but we have 12 here thats why we get an error

AttributeError: module 'numpy' has no attribute 'arrange'

In [81]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [82]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

numpy masking or filter

In [84]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
id(mat)

2622393444048

In [86]:
mat.shape

(10, 10)

In [87]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [89]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
mat[mat==50]

array([50])

In [91]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [92]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])